#ifndef RS274NGC_RETURN_HH
#define RS274NGC_RETURN_HH
#include "interp_return.h"
#define NCE_A_FILE_IS_ALREADY_OPEN EMC_I18N("A file is already open")
#define NCE_ALL_AXES_MISSING_WITH_G92 EMC_I18N("All axes missing with g92")
#define NCE_ALL_AXES_MISSING_WITH_MOTION_CODE EMC_I18N("All axes missing with motion code")
#define NCE_ARC_RADIUS_TOO_SMALL_TO_REACH_END_POINT EMC_I18N("Arc radius too small to reach end point")
#define NCE_ARGUMENT_TO_ACOS_OUT_OF_RANGE EMC_I18N("Argument to acos out of range")
#define NCE_ARGUMENT_TO_ASIN_OUT_OF_RANGE EMC_I18N("Argument to asin out of range")
#define NCE_ATTEMPT_TO_DIVIDE_BY_ZERO EMC_I18N("Attempt to divide by zero")
#define NCE_ATTEMPT_TO_RAISE_NEGATIVE_TO_NON_INTEGER_POWER EMC_I18N("Attempt to raise negative to non integer power")
#define NCE_BAD_CHARACTER_USED EMC_I18N("Bad character used")
#define NCE_BAD_FORMAT_UNSIGNED_INTEGER EMC_I18N("Bad format unsigned integer")
#define NCE_BAD_NUMBER_FORMAT EMC_I18N("Bad number format")
#define NCE_BUG_BAD_G_CODE_MODAL_GROUP_0 EMC_I18N("Bug bad g code modal group 0")
#define NCE_BUG_CODE_NOT_G0_OR_G1 EMC_I18N("Bug code not g0 or g1")
#define NCE_BUG_CODE_NOT_G17_G18_OR_G19 EMC_I18N("Bug code not g17 g18 or g19")
#define NCE_BUG_CODE_NOT_G20_OR_G21 EMC_I18N("Bug code not g20 or g21")
#define NCE_BUG_CODE_NOT_G28_OR_G30 EMC_I18N("Bug code not g28 or g30")
#define NCE_BUG_CODE_NOT_G2_OR_G3 EMC_I18N("Bug code not g2 or g3")
#define NCE_BUG_CODE_NOT_G40_G41_OR_G42 EMC_I18N("Bug code not g40 g41 or g42")
#define NCE_BUG_CODE_NOT_G43_OR_G49 EMC_I18N("Bug code not g43 or g49")
#define NCE_BUG_CODE_NOT_G4_G10_G28_G30_G53_OR_G92_SERIES EMC_I18N("Bug code not g4 g10 g28 g30 g53 or g92 series")
#define NCE_BUG_CODE_NOT_G61_G61_1_OR_G64 EMC_I18N("Bug code not g61 g61.1 or g64")
#define NCE_BUG_CODE_NOT_G90_OR_G91 EMC_I18N("Bug code not g90 or g91")
#define NCE_BUG_CODE_NOT_G93_OR_G94 EMC_I18N("Bug code not g93 or g94")
#define NCE_BUG_CODE_NOT_G98_OR_G99 EMC_I18N("Bug code not g98 or g99")
#define NCE_BUG_CODE_NOT_IN_G92_SERIES EMC_I18N("Bug code not in g92 series")
#define NCE_BUG_CODE_NOT_IN_RANGE_G54_TO_G593 EMC_I18N("Bug code not in range g54 to g593")
#define NCE_BUG_CODE_NOT_M0_M1_M2_M30_M60 EMC_I18N("Bug code not m0 m1 m2 m30 m60")
#define NCE_BUG_DISTANCE_MODE_NOT_G90_OR_G91 EMC_I18N("Bug distance mode not g90 or g91")
#define NCE_BUG_FUNCTION_SHOULD_NOT_HAVE_BEEN_CALLED EMC_I18N("Bug function should not have been called")
#define NCE_BUG_IN_TOOL_RADIUS_COMP EMC_I18N("Bug in tool radius comp")
#define NCE_BUG_PLANE_NOT_XY_YZ_OR_XZ EMC_I18N("Bug plane not xy yz or xz")
#define NCE_BUG_SIDE_NOT_RIGHT_OR_LEFT EMC_I18N("Bug side not right or left")
#define NCE_BUG_UNKNOWN_MOTION_CODE EMC_I18N("Bug unknown motion code")
#define NCE_BUG_UNKNOWN_OPERATION EMC_I18N("Bug unknown operation")
#define NCE_CANNOT_CHANGE_AXIS_OFFSETS_WITH_CUTTER_RADIUS_COMP EMC_I18N("Cannot change axis offsets with cutter radius comp")
#define NCE_CANNOT_CHANGE_UNITS_WITH_CUTTER_RADIUS_COMP EMC_I18N("Cannot change units with cutter radius comp")
#define NCE_CANNOT_CREATE_BACKUP_FILE EMC_I18N("Cannot create backup file")
#define NCE_CANNOT_DO_G1_WITH_ZERO_FEED_RATE EMC_I18N("Cannot do g1 with zero feed rate")
#define NCE_CANNOT_DO_ZERO_REPEATS_OF_CYCLE EMC_I18N("Cannot do zero repeats of cycle")
#define NCE_CANNOT_MAKE_ARC_WITH_ZERO_FEED_RATE EMC_I18N("Cannot make arc with zero feed rate")
#define NCE_CANNOT_MOVE_ROTARY_AXES_DURING_PROBING EMC_I18N("Cannot move rotary axes during probing")
#define NCE_CANNOT_OPEN_BACKUP_FILE EMC_I18N("Cannot open backup file")
#define NCE_CANNOT_OPEN_VARIABLE_FILE EMC_I18N("Cannot open variable file")
#define NCE_CANNOT_PROBE_IN_INVERSE_TIME_FEED_MODE EMC_I18N("Cannot probe in inverse time feed mode")
#define NCE_CANNOT_PROBE_WITH_CUTTER_RADIUS_COMP_ON EMC_I18N("Cannot probe with cutter radius comp on")
#define NCE_CANNOT_PROBE_WITH_ZERO_FEED_RATE EMC_I18N("Cannot probe with zero feed rate")
#define NCE_CANNOT_PUT_A_B_IN_CANNED_CYCLE EMC_I18N("Cannot put a b in canned cycle")
#define NCE_CANNOT_PUT_A_C_IN_CANNED_CYCLE EMC_I18N("Cannot put a c in canned cycle")
#define NCE_CANNOT_PUT_AN_A_IN_CANNED_CYCLE EMC_I18N("Cannot put an a in canned cycle")
#define NCE_CANNOT_TURN_CUTTER_RADIUS_COMP_ON_OUT_OF_XY_PLANE EMC_I18N("Cannot turn cutter radius comp on out of xy plane")
#define NCE_CANNOT_TURN_CUTTER_RADIUS_COMP_ON_WHEN_ON EMC_I18N("Cannot turn cutter radius comp on when on")
#define NCE_CANNOT_USE_A_WORD EMC_I18N("Cannot use a word")
#define NCE_CANNOT_USE_AXIS_VALUES_WITH_G80 EMC_I18N("Cannot use axis values with g80")
#define NCE_CANNOT_USE_AXIS_VALUES_WITHOUT_A_G_CODE_THAT_USES_THEM EMC_I18N("Cannot use axis values without a g code that uses them")
#define NCE_CANNOT_USE_B_WORD EMC_I18N("Cannot use b word")
#define NCE_CANNOT_USE_C_WORD EMC_I18N("Cannot use c word")
#define NCE_CANNOT_USE_G28_OR_G30_WITH_CUTTER_RADIUS_COMP EMC_I18N("Cannot use g28 or g30 with cutter radius comp")
#define NCE_CANNOT_USE_G53_INCREMENTAL EMC_I18N("Cannot use g53 incremental")
#define NCE_CANNOT_USE_G53_WITH_CUTTER_RADIUS_COMP EMC_I18N("Cannot use g53 with cutter radius comp")
#define NCE_CANNOT_USE_TWO_G_CODES_THAT_BOTH_USE_AXIS_VALUES EMC_I18N("Cannot use two g codes that both use axis values")
#define NCE_CANNOT_USE_XZ_PLANE_WITH_CUTTER_RADIUS_COMP EMC_I18N("Cannot use xz plane with cutter radius comp")
#define NCE_CANNOT_USE_YZ_PLANE_WITH_CUTTER_RADIUS_COMP EMC_I18N("Cannot use yz plane with cutter radius comp")
#define NCE_COMMAND_TOO_LONG EMC_I18N("Command too long")
#define NCE_CONCAVE_CORNER_WITH_CUTTER_RADIUS_COMP EMC_I18N("Concave corner with cutter radius comp")
#define NCE_COORDINATE_SYSTEM_INDEX_PARAMETER_5220_OUT_OF_RANGE EMC_I18N("Coordinate system index parameter 5220 out of range")
#define NCE_CURRENT_POINT_SAME_AS_END_POINT_OF_ARC EMC_I18N("Current point same as end point of arc")
#define NCE_CUTTER_GOUGING_WITH_CUTTER_RADIUS_COMP EMC_I18N("Cutter gouging with cutter radius comp")
#define NCE_D_WORD_WITH_NO_G41_OR_G42 EMC_I18N("D word with no g41 or g42")
#define NCE_DWELL_TIME_MISSING_WITH_G4 EMC_I18N("Dwell time missing with g4")
#define NCE_DWELL_TIME_P_WORD_MISSING_WITH_G82 EMC_I18N("Dwell time p word missing with g82")
#define NCE_DWELL_TIME_P_WORD_MISSING_WITH_G86 EMC_I18N("Dwell time p word missing with g86")
#define NCE_DWELL_TIME_P_WORD_MISSING_WITH_G88 EMC_I18N("Dwell time p word missing with g88")
#define NCE_DWELL_TIME_P_WORD_MISSING_WITH_G89 EMC_I18N("Dwell time p word missing with g89")
#define NCE_EQUAL_SIGN_MISSING_IN_PARAMETER_SETTING EMC_I18N("Equal sign missing in parameter setting")
#define NCE_F_WORD_MISSING_WITH_INVERSE_TIME_ARC_MOVE EMC_I18N("F word missing with inverse time arc move")
#define NCE_F_WORD_MISSING_WITH_INVERSE_TIME_G1_MOVE EMC_I18N("F word missing with inverse time g1 move")
#define NCE_FILE_ENDED_WITH_NO_PERCENT_SIGN EMC_I18N("File ended with no percent sign")
#define NCE_FILE_ENDED_WITH_NO_PERCENT_SIGN_OR_PROGRAM_END EMC_I18N("File ended with no percent sign or program end")
#define NCE_FILE_NAME_TOO_LONG EMC_I18N("File name too long")
#define NCE_G_CODE_OUT_OF_RANGE EMC_I18N("G code out of range")
#define NCE_I_WORD_GIVEN_FOR_ARC_IN_YZ_PLANE EMC_I18N("I word given for arc in yz plane")
#define NCE_I_WORD_MISSING_WITH_G87 EMC_I18N("I word missing with g87")
#define NCE_I_WORD_WITH_NO_G2_OR_G3_G76_OR_G87_TO_USE_IT EMC_I18N("I word with no g2, g3, g87, or g43 to use it")
#define NCE_J_WORD_GIVEN_FOR_ARC_IN_XZ_PLANE EMC_I18N("J word given for arc in xz plane")
#define NCE_J_WORD_MISSING_WITH_G87 EMC_I18N("J word missing with g87")
#define NCE_J_WORD_WITH_NO_G2_OR_G3_G76_OR_G87_TO_USE_IT EMC_I18N("J word with no g2, g3 or g87 to use it")
#define NCE_K_WORD_GIVEN_FOR_ARC_IN_XY_PLANE EMC_I18N("K word given for arc in xy plane")
#define NCE_K_WORD_MISSING_WITH_G87 EMC_I18N("K word missing with g87")
#define NCE_K_WORD_WITH_NO_G2_OR_G3_G76_OR_G87_TO_USE_IT EMC_I18N("K word with no g2, g3, g33, g33.1, g76, g87, or g43.1 to use it")
#define NCE_L_WORD_WITH_NO_CANNED_CYCLE_OR_G10 EMC_I18N("L word with no canned cycle, g10, or g76 to use it")
#define NCE_LEFT_BRACKET_MISSING_AFTER_SLASH_WITH_ATAN EMC_I18N("Left bracket missing after slash with atan")
#define NCE_LEFT_BRACKET_MISSING_AFTER_UNARY_OPERATION_NAME EMC_I18N("Left bracket missing after unary operation name")
#define NCE_LINE_NUMBER_GREATER_THAN_99999 EMC_I18N("Line number greater than 99999")
#define NCE_LINE_WITH_G10_DOES_NOT_HAVE_L2 EMC_I18N("Line with g10 does not have l2")
#define NCE_M_CODE_GREATER_THAN_199 EMC_I18N("M code greater than 199")
#define NCE_MIXED_RADIUS_IJK_FORMAT_FOR_ARC EMC_I18N("Mixed radius ijk format for arc")
#define NCE_MULTIPLE_A_WORDS_ON_ONE_LINE EMC_I18N("Multiple a words on one line")
#define NCE_MULTIPLE_B_WORDS_ON_ONE_LINE EMC_I18N("Multiple b words on one line")
#define NCE_MULTIPLE_C_WORDS_ON_ONE_LINE EMC_I18N("Multiple c words on one line")
#define NCE_MULTIPLE_D_WORDS_ON_ONE_LINE EMC_I18N("Multiple d words on one line")
#define NCE_MULTIPLE_F_WORDS_ON_ONE_LINE EMC_I18N("Multiple f words on one line")
#define NCE_MULTIPLE_H_WORDS_ON_ONE_LINE EMC_I18N("Multiple h words on one line")
#define NCE_MULTIPLE_I_WORDS_ON_ONE_LINE EMC_I18N("Multiple i words on one line")
#define NCE_MULTIPLE_J_WORDS_ON_ONE_LINE EMC_I18N("Multiple j words on one line")
#define NCE_MULTIPLE_K_WORDS_ON_ONE_LINE EMC_I18N("Multiple k words on one line")
#define NCE_MULTIPLE_L_WORDS_ON_ONE_LINE EMC_I18N("Multiple l words on one line")
#define NCE_MULTIPLE_P_WORDS_ON_ONE_LINE EMC_I18N("Multiple p words on one line")
#define NCE_MULTIPLE_Q_WORDS_ON_ONE_LINE EMC_I18N("Multiple q words on one line")
#define NCE_MULTIPLE_R_WORDS_ON_ONE_LINE EMC_I18N("Multiple r words on one line")
#define NCE_MULTIPLE_S_WORDS_ON_ONE_LINE EMC_I18N("Multiple s words on one line")
#define NCE_MULTIPLE_T_WORDS_ON_ONE_LINE EMC_I18N("Multiple t words on one line")
#define NCE_MULTIPLE_X_WORDS_ON_ONE_LINE EMC_I18N("Multiple x words on one line")
#define NCE_MULTIPLE_Y_WORDS_ON_ONE_LINE EMC_I18N("Multiple y words on one line")
#define NCE_MULTIPLE_Z_WORDS_ON_ONE_LINE EMC_I18N("Multiple z words on one line")
#define NCE_MUST_USE_G0_OR_G1_WITH_G53 EMC_I18N("Must use g0 or g1 with g53")
#define NCE_NEGATIVE_ARGUMENT_TO_SQRT EMC_I18N("Negative argument to sqrt")
#define NCE_NEGATIVE_D_WORD_TOOL_RADIUS_INDEX_USED EMC_I18N("Negative d word tool radius index used")
#define NCE_NEGATIVE_F_WORD_USED EMC_I18N("Negative f word used")
#define NCE_NEGATIVE_G_CODE_USED EMC_I18N("Negative g code used")
#define NCE_NEGATIVE_H_WORD_USED EMC_I18N("Negative h word used")
#define NCE_NEGATIVE_L_WORD_USED EMC_I18N("Negative l word used")
#define NCE_NEGATIVE_M_CODE_USED EMC_I18N("Negative m code used")
#define NCE_NEGATIVE_OR_ZERO_Q_VALUE_USED EMC_I18N("Negative or zero q value used")
#define NCE_NEGATIVE_P_WORD_USED EMC_I18N("Negative p word used")
#define NCE_NEGATIVE_SPINDLE_SPEED_USED EMC_I18N("Negative spindle speed used")
#define NCE_NEGATIVE_TOOL_ID_USED EMC_I18N("Negative tool id used")
#define NCE_NESTED_COMMENT_FOUND EMC_I18N("Nested comment found")
#define NCE_NO_CHARACTERS_FOUND_IN_READING_REAL_VALUE EMC_I18N("No characters found in reading real value")
#define NCE_NO_DIGITS_FOUND_WHERE_REAL_NUMBER_SHOULD_BE EMC_I18N("No digits found where real number should be")
#define NCE_NON_INTEGER_VALUE_FOR_INTEGER EMC_I18N("Non integer value for integer")
#define NCE_NULL_MISSING_AFTER_NEWLINE EMC_I18N("Null missing after newline")
#define NCE_OFFSET_INDEX_MISSING EMC_I18N("Offset index missing")
#define NCE_P_VALUE_NOT_AN_INTEGER_WITH_G10_L2 EMC_I18N("P value not an integer with g10 l2")
#define NCE_P_VALUE_OUT_OF_RANGE_WITH_G10_L2 EMC_I18N("P value out of range with g10 l2")
#define NCE_PARAMETER_FILE_OUT_OF_ORDER EMC_I18N("Parameter file out of order")
#define NCE_PARAMETER_NUMBER_OUT_OF_RANGE EMC_I18N("Parameter number out of range")
#define NCE_PARAMETER_NUMBER_READONLY EMC_I18N("Parameter is readonly")
#define NCE_Q_WORD_MISSING_WITH_G83 EMC_I18N("Q word missing with g83")
#define NCE_Q_WORD_WITH_NO_G83_OR_M66 EMC_I18N("Q word with no g83 or m66")
#define NCE_QUEUE_IS_NOT_EMPTY_AFTER_PROBING EMC_I18N("Queue is not empty after probing")
#define NCE_R_CLEARANCE_PLANE_UNSPECIFIED_IN_CYCLE EMC_I18N("R clearance plane unspecified in cycle")
#define NCE_R_I_J_K_WORDS_ALL_MISSING_FOR_ARC EMC_I18N("R i j k words all missing for arc")
#define NCE_R_LESS_THAN_X_IN_CYCLE_IN_YZ_PLANE EMC_I18N("R less than x in cycle in yz plane")
#define NCE_R_LESS_THAN_Y_IN_CYCLE_IN_XZ_PLANE EMC_I18N("R less than y in cycle in xz plane")
#define NCE_R_LESS_THAN_Z_IN_CYCLE_IN_XY_PLANE EMC_I18N("R less than z in cycle in xy plane")
#define NCE_R_WORD_WITH_NO_G_CODE_THAT_USES_IT EMC_I18N("R word with no g code that uses it")
#define NCE_RADIUS_TO_END_OF_ARC_DIFFERS_FROM_RADIUS_TO_START EMC_I18N("Radius to end of arc differs from radius to start")
#define NCE_RADIUS_TOO_SMALL_TO_REACH_END_POINT EMC_I18N("Radius too small to reach end point")
#define NCE_REQUIRED_PARAMETER_MISSING EMC_I18N("Required parameter missing")
#define NCE_SELECTED_TOOL_SLOT_NUMBER_TOO_LARGE EMC_I18N("Selected tool slot number too large")
#define NCE_SLASH_MISSING_AFTER_FIRST_ATAN_ARGUMENT EMC_I18N("Slash missing after first atan argument")
#define NCE_SPINDLE_NOT_TURNING_CLOCKWISE_IN_G84 EMC_I18N("Spindle not turning clockwise in g84")
#define NCE_SPINDLE_NOT_TURNING_IN_G86 EMC_I18N("Spindle not turning in g86")
#define NCE_SPINDLE_NOT_TURNING_IN_G87 EMC_I18N("Spindle not turning in g87")
#define NCE_SPINDLE_NOT_TURNING_IN_G88 EMC_I18N("Spindle not turning in g88")
#define NCE_SSCANF_FAILED EMC_I18N("Sscanf failed")
#define NCE_START_POINT_TOO_CLOSE_TO_PROBE_POINT EMC_I18N("Start point too close to probe point")
#define NCE_TOO_MANY_M_CODES_ON_LINE EMC_I18N("Too many m codes on line")
#define NCE_TOOL_LENGTH_OFFSET_INDEX_TOO_BIG EMC_I18N("Tool length offset index too big")
#define NCE_POCKET_MAX_TOO_LARGE EMC_I18N("Pocket max too large")
#define NCE_TOOL_RADIUS_INDEX_TOO_BIG EMC_I18N("Tool radius index too big")
#define NCE_TOOL_RADIUS_NOT_LESS_THAN_ARC_RADIUS_WITH_COMP EMC_I18N("Tool radius not less than arc radius with comp")
#define NCE_TWO_G_CODES_USED_FROM_SAME_MODAL_GROUP EMC_I18N("Two g codes used from same modal group")
#define NCE_TWO_M_CODES_USED_FROM_SAME_MODAL_GROUP EMC_I18N("Two m codes used from same modal group")
#define NCE_UNABLE_TO_OPEN_FILE EMC_I18N("Unable to open file <%s>")
#define NCE_UNCLOSED_COMMENT_FOUND EMC_I18N("Unclosed comment found")
#define NCE_UNCLOSED_EXPRESSION EMC_I18N("Unclosed expression")
#define NCE_UNKNOWN_G_CODE_USED EMC_I18N("Unknown g code used")
#define NCE_UNKNOWN_M_CODE_USED EMC_I18N("Unknown m code used")
#define NCE_UNKNOWN_OPERATION EMC_I18N("Unknown operation")
#define NCE_UNKNOWN_OPERATION_NAME_STARTING_WITH_A EMC_I18N("Unknown operation name starting with a")
#define NCE_UNKNOWN_OPERATION_NAME_STARTING_WITH_M EMC_I18N("Unknown operation name starting with m")
#define NCE_UNKNOWN_OPERATION_NAME_STARTING_WITH_O EMC_I18N("Unknown operation name starting with o")
#define NCE_UNKNOWN_OPERATION_NAME_STARTING_WITH_X EMC_I18N("Unknown operation name starting with x")
#define NCE_UNKNOWN_WORD_STARTING_WITH_A EMC_I18N("Unknown word starting with a")
#define NCE_UNKNOWN_WORD_STARTING_WITH_C EMC_I18N("Unknown word starting with c")
#define NCE_UNKNOWN_WORD_STARTING_WITH_E EMC_I18N("Unknown word starting with e")
#define NCE_UNKNOWN_WORD_STARTING_WITH_F EMC_I18N("Unknown word starting with f")
#define NCE_UNKNOWN_WORD_STARTING_WITH_L EMC_I18N("Unknown word starting with l")
#define NCE_UNKNOWN_WORD_STARTING_WITH_R EMC_I18N("Unknown word starting with r")
#define NCE_UNKNOWN_WORD_STARTING_WITH_S EMC_I18N("Unknown word starting with s")
#define NCE_UNKNOWN_WORD_STARTING_WITH_T EMC_I18N("Unknown word starting with t")
#define NCE_UNKNOWN_WORD_WHERE_UNARY_OPERATION_COULD_BE EMC_I18N("Unknown word where unary operation could be")
#define NCE_X_AND_Y_WORDS_MISSING_FOR_ARC_IN_XY_PLANE EMC_I18N("X and y words missing for arc in xy plane")
#define NCE_X_AND_Z_WORDS_MISSING_FOR_ARC_IN_XZ_PLANE EMC_I18N("X and z words missing for arc in xz plane")
#define NCE_X_VALUE_UNSPECIFIED_IN_YZ_PLANE_CANNED_CYCLE EMC_I18N("X value unspecified in yz plane canned cycle")
#define NCE_X_Y_Z_A_B_C_U_V_AND_W_WORDS_ALL_MISSING_WITH_G38_2 EMC_I18N("X, y, z, a, b, c, u, v, and w words all missing with g38.2")
#define NCE_Y_AND_Z_WORDS_MISSING_FOR_ARC_IN_YZ_PLANE EMC_I18N("Y and z words missing for arc in yz plane")
#define NCE_Y_VALUE_UNSPECIFIED_IN_XZ_PLANE_CANNED_CYCLE EMC_I18N("Y value unspecified in xz plane canned cycle")
#define NCE_Z_VALUE_UNSPECIFIED_IN_XY_PLANE_CANNED_CYCLE EMC_I18N("Z value unspecified in xy plane canned cycle")
#define NCE_ZERO_OR_NEGATIVE_ARGUMENT_TO_LN EMC_I18N("Zero or negative argument to ln")
#define NCE_ZERO_RADIUS_ARC EMC_I18N("Zero radius arc")
#define NCE_K_WORD_MISSING_WITH_G33 EMC_I18N("K word missing with g33/g33.1")
#define NCE_F_WORD_USED_WITH_G33 EMC_I18N("F word used with a g33/g33.1")
#define NCE_G33_NOT_SUPPORTED EMC_I18N("G33 not supported")
#define NCE_CANNED_CYCLES_NOT_SUPPORTED EMC_I18N("Canned cycles not supported")
#define NCE_UNKNOWN_OPERATION_NAME_STARTING_WITH_E EMC_I18N("Unknown operation name starting with e")
#define NCE_UNKNOWN_OPERATION_NAME_STARTING_WITH_N EMC_I18N("Unknown operation name starting with n")
#define NCE_UNKNOWN_OPERATION_NAME_STARTING_WITH_G EMC_I18N("Unknown operation name starting with g")
#define NCE_UNKNOWN_OPERATION_NAME_STARTING_WITH_L EMC_I18N("Unknown operation name starting with l")
#define NCE_TOO_MANY_SUBROUTINE_PARAMETERS EMC_I18N("Too many subroutine parameters")
#define NCE_TOO_MANY_SUBROUTINE_LEVELS EMC_I18N("Too many subroutine levels")
#define NCE_UNKNOWN_COMMAND_IN_O_LINE EMC_I18N("Unknown control command in o word")
#define NCE_TOO_MANY_OWORD_LABELS EMC_I18N("Too many oword labels")
#define NCE_UNKNOWN_OWORD_NUMBER EMC_I18N("Unknown oword number")
#define NCE_NESTED_SUBROUTINE_DEFN EMC_I18N("Nested subroutine definition")
#define NCE_NOT_IN_SUBROUTINE_DEFN EMC_I18N("Not in subroutine definition")
#define NCE_RETURN_OUTSIDE_OF_SUBROUTINE EMC_I18N("Return outside of subroutine")
#define NCE_FILE_NOT_OPEN EMC_I18N("File not open")
#define NCE_TXX_MISSING_FOR_M6 EMC_I18N("Need tool prepared -Txx- for toolchange")
#define NCE_CANNOT_CHANGE_PLANES_WITH_CUTTER_RADIUS_COMP_ON EMC_I18N("Cannot change planes with cutter radius compensation on")
#define NCE_RADIUS_COMP_ONLY_IN_XY_OR_XZ EMC_I18N("Cutter radius compensation allowed only in XY, XZ planes")
#define NCE_P_WORD_MISSING_WITH_G76 EMC_I18N("P word missing with G76")
#define NCE_I_J_OR_K_WORDS_MISSING_WITH_G76 EMC_I18N("I J or K words missing with G76")
#define NCE_CANNOT_MOVE_ROTARY_AXES_WITH_G76 EMC_I18N("Cannot move rotary axes with G76")
#define NCE_MULTIPLE_E_WORDS_ON_ONE_LINE EMC_I18N("Multiple e words on one line")
#define NCE_NAMED_PARAMETER_NOT_TERMINATED EMC_I18N("Named parameter not terminated")
#define NCE_NAMED_OWORD_NOT_TERMINATED EMC_I18N("Named oword not terminated")
#define NCE_NAMED_OWORD_NOT_DEFINED EMC_I18N("Named oword not defined")
#define NCE_OUT_OF_MEMORY EMC_I18N("Out of memory")
#define NCE_S_WORD_MISSING_WITH_G96 EMC_I18N("S word missing with G96")
#define NCE_QUEUE_IS_NOT_EMPTY_AFTER_INPUT EMC_I18N("Queue is not empty after external input")
#define NCE_ANALOG_INPUT_WITH_WAIT_NOT_IMMEDIATE EMC_I18N("Can't select analog input with wait type != immediate return")
#define NCE_ZERO_TIMEOUT_WITH_WAIT_NOT_IMMEDIATE EMC_I18N("Zero timeout with wait type != immediate return")
#define NCE_BOTH_DIGITAL_AND_ANALOG_INPUT_SELECTED EMC_I18N("Invalid to select both a digital and an analog input with M66")
#define NCE_INVALID_OR_MISSING_P_AND_E_WORDS_FOR_WAIT_INPUT EMC_I18N("Need to have either a valid P or a valid E word with M66")
#define NCE_Q_WORD_MISSING_WITH_G73 EMC_I18N("Q word missing with g73")
#define NCE_DIGITAL_INPUT_INVALID_ON_M66 EMC_I18N("Digital input selected out of bounds")
#define NCE_ANALOG_INPUT_INVALID_ON_M66 EMC_I18N("Analog input selected out of bounds")
#define NCE_W_VALUE_UNSPECIFIED_IN_UV_PLANE_CANNED_CYCLE EMC_I18N("W value unspecified in UV plane canned cycle")
#define NCE_U_VALUE_UNSPECIFIED_IN_VW_PLANE_CANNED_CYCLE EMC_I18N("U value unspecified in VW plane canned cycle")
#define NCE_V_VALUE_UNSPECIFIED_IN_UW_PLANE_CANNED_CYCLE EMC_I18N("V value unspecified in UW plane canned cycle")
#define NCE_R_LESS_THAN_W_IN_CYCLE_IN_UV_PLANE EMC_I18N("R less than W in cycle in UV plane")
#define NCE_R_LESS_THAN_U_IN_CYCLE_IN_VW_PLANE EMC_I18N("R less than U in cycle in VW plane")
#define NCE_R_LESS_THAN_V_IN_CYCLE_IN_UW_PLANE EMC_I18N("R less than V in cycle in UW plane")
#endif
